name = "bento"
main = "src/index.ts"
workers_dev = true

[vars]
BASE_URL = "http://127.0.0.1:8787"

# Override values for `--env production` usage
[env.production]
routes = [
	{ pattern = "bento.dispatcherpersada.workers.dev", custom_domain = true }
]

[env.production.vars]
BASE_URL = "https://bento.dispatcherpersada.workers.dev"
